### ISSUE TITLE
[ upstream ] Fails to build due to Idris totality checker fix

### ISSUE THREAD

**Issue by stefan-hoeck** [mattpolzin/ncurses-idris#34]
Some functions are no longer accepted by Idris as being total due to a fix in idris-lang/idris2#2953 . This might be related to idris-lang/idris2#2954 but I haven't looked into it in detail.

**Comment by dunhamsteve** [comment]
I think this one actually diverges:
```idris
hasWindowWithin : InWindow w s => HasWindow w s
hasWindowWithin {s = (Active _ _ ((MkWindow name _ _) ** Here) _)} @{IsCurrentWindow} = ItHasWindow
hasWindowWithin {s = (Active _ _ ((MkWindow name _ _) ** (There x)) _)} @{IsCurrentWindow} = hasWindowWithin
```
Prior to idris-lang/Idris2#2953, it was accepting with this criteria:
```
Size change: Control.NCurses.hasWindowWithin: [Just (0, Same), Just (0, Smaller), Just (2, Same)]
```
where
```idris
Control.NCurses.hasWindowWithin : {0 s : CursesState} -> {0 w : String} -> InWindow w s => HasWindow w s
```
So I think it was picking up the `name` for the `w` arg on recursion, and it is smaller than the `s` so it erroneously assumed things got smaller, but it's keeping `s` the same and just picking up the same `{w=name}` each time out of `s`.
